### ISSUE TITLE
CSS: 100% font size - 100% of what?

### ISSUE THREAD

**Issue by yangbo5207** [yangbo5207/everyday#13]
You can set the default font-size in the body, like so
```css
body {
    font-size: 14px;
}
```
now, the font-size of all my page will inherit a font-size of 14px.
Then I want a DIV tag that  className is 'inner' have a font-size 10% smaller than body. I simply do.
```css
.inner {
    font-size: 90%;
}
```
the same mean, if I want this DIV's font-size 10% bigger than body, I will set
```css
div {
    font-size: 110%;
}
```
