### ISSUE TITLE
CSS: 两/三列布局的实现

### ISSUE THREAD

**Issue by yangbo5207** [yangbo5207/everyday#46]
#### CSS: 两列/三列布局详解

所谓的两列/三列布局，一般来说，指的是左右两边的列固定宽度，中间列宽度自适应。实现方式也有很多种，在实际应用中也经常会遇到这类型的需求，因此这里将自己所遇到的方法总结一下。

##### 1. 使用BFC的原理实现
BFC的规则之一，就是BFC区域，不会与float box重叠，因此我们可以利用这一点来实现3列布局。

html代码如下
```html
<div class="left"></div>
<div class="right"></div>
<div class="main"></div>
```
css代码如下
```css
.left {
  float: left;
  margin-right: 10px;
  width: 100px;
  height: 100px;
  background-color: orange;
}
.right {
  float: right;
  margin-left: 10px;
  width: 100px;
  height: 100px;
  background-color: orange;
}
.main {
  height: 100px;
  background-color: green;
  overflow: hidden;
}
```
实例地址： http://codepen.io/anon/pen/jWJpEo
兼容性： IE6+ 都没有问题
缺点：主要内容模块无法最先加载，当页面中内容较多时会影响用户体验。因此为了解决这个问题，有了如下的布局方案`双飞翼布局`
> 在IE6，IE7中使用`overflow:hidden`会没有效果，子元素超出父元素部分任然不会隐藏，解决办法就是在该元素的父级添加如下属性即可`position: relative`。这个问题并不影响本例中的布局实现。

##### 2.双飞翼布局
这种布局方案最早由淘宝提出，主要为了主列能够被最先加载。
实现原理：
1. 让主列外面添加一个wrap，主列wrap，以及2子列都左浮动。
2. 设置主列wrap宽度为100%，将子列的`margin-left`设置为负值，让子列能够排列在左右两侧。
3. 这是主列的`margin-left`与`margin-right`比左右两列的宽度大一点，则可以设置出来主列与子列之间的间隙。
html代码如下
```html
<div class="wrap">
  <div class="main-content">
    <div class="main"></div>
  </div>
  <div class="left"></div>
  <div class="right"></div>
</div>
```
css代码如下
```css
.wrap {
  width: 100%;
}
.wrap::after {
  display: block;
  content: '';
  font-size: 0;
  height: 0;
  clear: both;
  zoom: 1;
}
.main-content {
  float: left;
  width: 100%;
}
.main {
  height: 100px;
  background-color: green;
  margin-left: 110px;
  margin-right: 110px;
}

.left {
  float: left;
  width: 100px;
  height: 100px;
  background-color: orange;
  margin-left: -100%;
}
.right {
  float: left;
  width: 100px;
  height: 100px;
  background-color: orange;
  margin-left: -100px;
}
```
实例地址： http://codepen.io/anon/pen/adMGer
兼容性: IE6+
缺点：和上面的方案相比，html代码结构更加复杂。所以我们按需选择自己需要的方案吧
