### ISSUE TITLE
css: 如何禁止选择文本

### ISSUE THREAD

**Issue by yangbo5207** [yangbo5207/everyday#47]
如果让整个页面都禁止选择，可以使用下面的css   

```css
body{
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

如果希望指定元素禁止选择

```css
*.unselectable {
   -moz-user-select: -moz-none;
   -khtml-user-select: none;
   -webkit-user-select: none;

   /*
     Introduced in IE 10.
     See http://ie.microsoft.com/testdrive/HTML5/msUserSelect/
   */
   -ms-user-select: none;
   user-select: none;
}
```
