### ISSUE TITLE
css3: 在移动端使用overflow:scroll会导致滚动卡顿

### ISSUE THREAD

**Issue by yangbo5207** [yangbo5207/everyday#52]
因此在移动端尽量避免使用该属性，而选择  

``` css
.content {
    overflow: auto;
}
```

另外，在移动端的滚动中需要实现快速滚动和回弹的效果，只需要使用下面的属性即可  

``` css
.box {
    -webkit-overflow-scrolling: touch;
}
```

> 这个属性虽然能够通过硬件加速带来非常好的体验，但是却增加了内存消耗，因此一般在产生了大面积的overflow: auto时才会使用
