### ISSUE TITLE
CSS: 超出文字省略号

### ISSUE THREAD

**Issue by yangbo5207** [yangbo5207/everyday#58]
``` css
.test {
    display: block;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```
